openapi: 3.0.0
info:
  title: Live Answers API - OpenAPI 3.0
  description: api for live answers
  contact:
    email: paulagomenr@gmail.com
  license:
    name: MIT License
  version: 1.0.0

servers:
  - url: http://127.0.0.1:3333

tags:
  - name: questions
    description: Operations for questions
  - name: answers
    description: Operations for answers

paths:
  /api/questions:
    post:
      tags:
        - questions
      summary: Add a new question
      description: Add a new question
      requestBody:
        description: Store a new question
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionReq'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
            application/xml:
              schema:
                $ref: '#/components/schemas/Question'
  /api/questions/{question_id}:
    get:
      tags:
        - questions
      summary: Get a question
      description: Get a question
      parameters:
        - name: question_id
          in: path
          description: 'id of the question'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
            application/xml:
              schema:
                $ref: '#/components/schemas/Question'
  /api/question:
    get:
      tags:
        - questions
      summary: Get first question
      description: Get first question
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
            application/xml:
              schema:
                $ref: '#/components/schemas/Question'
  /api/questions/{question_id}/answers:
    get:
      tags:
        - answers
      summary: Get all answers
      description: Get all answers
      parameters:
        - name: question_id
          in: path
          description: 'id of the question'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Answer'
    post:
      tags:
        - answers
      summary: Add a new answer
      description: Add a new answer
      parameters:
        - name: question_id
          in: path
          description: 'id of the question'
          required: true
          schema:
            type: string
      requestBody:
        description: Store a new answer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnswerReq'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
            application/xml:
              schema:
                $ref: '#/components/schemas/Answer'
        '404':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Question not found'
components:
  schemas:
    QuestionReq:
      type: object
      properties:
        title:
          type: string
    Question:
      type: object
      allOf:
        - $ref: '#/components/schemas/QuestionReq'
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    AnswerReq:
      type: object
      properties:
        message:
          type: string
    Answer:
      type: object
      allOf:
        - $ref: '#/components/schemas/AnswerReq'
      properties:
        id:
          type: string
        questionId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
